/*     */ package com.veloria.login;
/*     */ 
/*     */ import java.io.File;
/*     */ import java.io.IOException;
/*     */ import java.nio.charset.StandardCharsets;
/*     */ import java.nio.file.Files;
/*     */ import java.util.ArrayDeque;
/*     */ import java.util.ArrayList;
/*     */ import java.util.Collections;
/*     */ import java.util.Deque;
/*     */ import java.util.LinkedHashMap;
/*     */ import java.util.List;
/*     */ import java.util.Map;
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ final class MiniYaml
/*     */ {
/* 286 */   private final Map<String, String> values = new LinkedHashMap<>(); private final Map<String, List<String>> lists = new LinkedHashMap<>();
/* 287 */   static MiniYaml load(File paramFile) throws IOException { MiniYaml miniYaml = new MiniYaml(); ArrayDeque<String> arrayDeque = new ArrayDeque(); ArrayDeque<Integer> arrayDeque1 = new ArrayDeque(); String str = null; for (String str1 : Files.readAllLines(paramFile.toPath(), StandardCharsets.UTF_8)) { if (str1.trim().isEmpty() || str1.trim().startsWith("#")) continue;  byte b; for (b = 0; b < str1.length() && str1.charAt(b) == ' '; b++); String str2 = str1.trim(); if (str2.startsWith("- ")) { if (str != null) ((List<String>)miniYaml.lists.computeIfAbsent(str, paramString -> new ArrayList())).add(VeloriaLogin.unquote(str2.substring(2).trim()));  continue; }  for (str = null; !arrayDeque1.isEmpty() && b < ((Integer)arrayDeque1.peek()).intValue(); ) { arrayDeque1.pop(); arrayDeque.pop(); }  int i = str2.indexOf(':'); if (i < 0) continue;  String str3 = str2.substring(0, i).trim(), str4 = str2.substring(i + 1).trim(); if (str4.isEmpty()) { String str5 = path(arrayDeque, str3); arrayDeque.push(str3); arrayDeque1.push(Integer.valueOf(b + 2)); if (str3.equals("lines")) str = str5;  continue; }  miniYaml.values.put(path(arrayDeque, str3), VeloriaLogin.unquote(str4)); }  return miniYaml; }
/* 288 */   static String path(Deque<String> paramDeque, String paramString) { ArrayList<String> arrayList = new ArrayList<>(paramDeque); Collections.reverse(arrayList); if (arrayList.isEmpty()) return paramString;  arrayList.add(paramString); return String.join(".", (Iterable)arrayList); }
/* 289 */   String get(String paramString1, String paramString2) { return this.values.getOrDefault(paramString1, paramString2); } boolean getBoolean(String paramString, boolean paramBoolean) { return Boolean.parseBoolean(get(paramString, String.valueOf(paramBoolean))); } long getLong(String paramString, long paramLong) { try { return Long.parseLong(get(paramString, String.valueOf(paramLong))); } catch (Exception exception) { return paramLong; }  } int getInt(String paramString, int paramInt) { return (int)getLong(paramString, paramInt); } double getDouble(String paramString, double paramDouble) { try { return Double.parseDouble(get(paramString, String.valueOf(paramDouble))); } catch (Exception exception) { return paramDouble; }  } List<String> list(String paramString) { return this.lists.getOrDefault(paramString, new ArrayList<>()); } void set(String paramString1, String paramString2) { this.values.put(paramString1, paramString2); }
/* 290 */   void save(File paramFile) throws IOException { LinkedHashMap<Object, Object> linkedHashMap = new LinkedHashMap<>(); for (Map.Entry<String, String> entry : this.values.entrySet()) put((Map)linkedHashMap, (String)entry.getKey(), (String)entry.getValue());  StringBuilder stringBuilder = new StringBuilder(); write((Map)linkedHashMap, stringBuilder, 0); Files.writeString(paramFile.toPath(), stringBuilder.toString(), StandardCharsets.UTF_8, new java.nio.file.OpenOption[0]); } static void put(Map<String, Object> paramMap, String paramString1, String paramString2) { String[] arrayOfString; Map<String, Object> map; byte b;
/* 291 */     for (arrayOfString = paramString1.split("\\."), map = paramMap, b = 0; b < arrayOfString.length - 1; ) { Object<Object, Object> object = (Object<Object, Object>)map.get(arrayOfString[b]); if (!(object instanceof Map)) { object = (Object<Object, Object>)new LinkedHashMap<>(); map.put(arrayOfString[b], object); }  map = (Map)object; b++; }  map.put(arrayOfString[arrayOfString.length - 1], paramString2); } static void write(Map<String, Object> paramMap, StringBuilder paramStringBuilder, int paramInt) {
/* 292 */     for (Map.Entry<String, Object> entry : paramMap.entrySet()) { paramStringBuilder.append("  ".repeat(paramInt)).append((String)entry.getKey()).append(": "); if (entry.getValue() instanceof Map) { paramStringBuilder.append('\n'); write((Map<String, Object>)entry.getValue(), paramStringBuilder, paramInt + 1); continue; }  paramStringBuilder.append('"').append(entry.getValue()).append("\"\n"); }
/*     */   
/*     */   }
/*     */ }


/* Location:              C:\Users\adasd\Downloads\VeloriaLogin-1.0.0-1.21.11.jar!\com\veloria\login\VeloriaLogin$MiniYaml.class
 * Java compiler version: 21 (65.0)
 * JD-Core Version:       1.1.3
 */